In [1]:
import numpy as np

In [30]:
a = np.zeros((10))
print(a)
a[4] = 1
print(a)
a2 = np.arange(10,31)
print(a2)
a3 = np.random.randint(100,size=(2,2))
print(a3)
a4 = np.random.rand(2,4)
print(a4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]
[[67 62]
 [26 56]]
[[0.20385278 0.17560834 0.75458986 0.65852569]
 [0.12172373 0.16108157 0.41913424 0.8249729 ]]


In [32]:
rng = np.random.default_rng()
a3 = rng.integers(0,100,(2,2))
print(a3)

[[39 80]
 [76  9]]


In [45]:
a6 = np.arange(35,75).reshape(10,4)
print(a6)

a7 = a6[::-1]
print(a7)

a8 = a6[1:-1, 2:]
print(a8)

[[35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]
 [47 48 49 50]
 [51 52 53 54]
 [55 56 57 58]
 [59 60 61 62]
 [63 64 65 66]
 [67 68 69 70]
 [71 72 73 74]]
[[71 72 73 74]
 [67 68 69 70]
 [63 64 65 66]
 [59 60 61 62]
 [55 56 57 58]
 [51 52 53 54]
 [47 48 49 50]
 [43 44 45 46]
 [39 40 41 42]
 [35 36 37 38]]
[[41 42]
 [45 46]
 [49 50]
 [53 54]
 [57 58]
 [61 62]
 [65 66]
 [69 70]]


In [59]:

a9 = a6[:,-1]
print(a9)

# a9_1 = a9.reshape(10,1)
# print(a9_1)

a9_1 = a6[:, -1:]
print(a9_1)

a10 = a9_1[::-1, -1:]
print(a10)

# a11 = np.random.randint(1,51,size=(5,6))
# print(a11)
# even11 = (a11 % 2 == 0)
# even_num = a11[(even11)]
# print(even_num)

ndarr = rng.integers(1,51,size=(5,6))
print(ndarr)
print(ndarr[ndarr%2 == 0])


[38 42 46 50 54 58 62 66 70 74]
[[38]
 [42]
 [46]
 [50]
 [54]
 [58]
 [62]
 [66]
 [70]
 [74]]
[[74]
 [70]
 [66]
 [62]
 [58]
 [54]
 [50]
 [46]
 [42]
 [38]]
[[ 4 34 10 50 14 39]
 [49 33  2 18 12 43]
 [40 30 10 36  4 44]
 [39 11 46 17 47 12]
 [49  2 35 33 13 36]]
[ 4 34 10 50 14  2 18 12 40 30 10 36  4 44 46 12  2 36]


In [61]:
a = np.array([[1,2],[3,4]])

expanded = np.expand_dims(a, 0)
print(expanded)
print(expanded.shape)

[[[1 2]
  [3 4]]]
(1, 2, 2)


In [62]:
a = np.array([[1,2],[3,4]])

expanded = np.expand_dims(a, 1)
print(expanded)
print(expanded.shape)

[[[1 2]]

 [[3 4]]]
(2, 1, 2)


In [63]:
a = np.array([[1,2],[3,4]])

expanded = np.expand_dims(a, 2)
print(expanded)
print(expanded.shape)

[[[1]
  [2]]

 [[3]
  [4]]]
(2, 2, 1)


In [65]:
np_ones = np.ones((1,2,1,3))
print(np_ones)

[[[[1. 1. 1.]]

  [[1. 1. 1.]]]]


In [66]:
squeezed = np.squeeze(np_ones)
print(squeezed)
print(squeezed.shape)

[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)


In [67]:
squeezed = np.squeeze(np_ones, 0)
print(squeezed)
print(squeezed.shape)

[[[1. 1. 1.]]

 [[1. 1. 1.]]]
(2, 1, 3)


In [68]:
squeezed = np.squeeze(np_ones, 2)
print(squeezed)
print(squeezed.shape)

[[[1. 1. 1.]
  [1. 1. 1.]]]
(1, 2, 3)


In [69]:
a=[1,2,2,3,3,3,4,4]

In [73]:
unique_a, indexes, counts = np.unique(a, return_index=True, return_counts=True,)
print(unique_a, counts, indexes)

[1 2 3 4] [1 2 3 2] [0 1 3 6]


In [79]:
a = np.array([1,4,2,3])
b = np.sort(a) # a[np.argsort(a)]
print(f"a {a}")
print(f"b {b}")
c = np.argsort(a)
print(f"c {c}")
print(f"cc {a[c]}")
print(a[c.sort()].flatten())
a.sort()
print(f"a {a}")

a [1 4 2 3]
b [1 2 3 4]
c [0 2 3 1]
cc [1 2 3 4]
[1 4 2 3]
a [1 2 3 4]


In [81]:
a = np.array([1,4,2,3])
np.mean(a)

2.5

In [82]:
np.std(a)

1.118033988749895

In [85]:
np.var(a)

1.25

In [86]:
np.max(a)

4

In [87]:
np.min(a)

1

In [88]:
np.sum(a)

10

In [89]:
np.prod(a)

24

In [90]:
np.median(a)

2.5

In [91]:
x = np.arange(15, dtype=np.int64).reshape(3,5)
x[1:,::2] = -99
x

array([[  0,   1,   2,   3,   4],
       [-99,   6, -99,   8, -99],
       [-99,  11, -99,  13, -99]], dtype=int64)

In [92]:
x.max(axis=1)

array([ 4,  8, 13], dtype=int64)

In [93]:
x.max(axis=0)

array([ 0, 11,  2, 13,  4], dtype=int64)

In [95]:
a = np.sort(x, axis=0)
print(a)

[[-99   1 -99   3 -99]
 [-99   6 -99   8 -99]
 [  0  11   2  13   4]]


In [97]:
b = np.sort(x, axis=1)
print(b)

[[  0   1   2   3   4]
 [-99 -99 -99   6   8]
 [-99 -99 -99  11  13]]


In [99]:
a = [1,1,2,3,4,5,5,5,5,7,8,9,10,11,24,100]
u_a = np.unique(a)
print(u_a)
print(np.max(u_a))
print(np.min(u_a))
print(np.mean(u_a))
print(np.sum(u_a))
print(np.median(a))

[  1   2   3   4   5   7   8   9  10  11  24 100]
100
1
15.333333333333334
184
5.0


In [122]:
x = np.arange(15, dtype=np.int64).reshape(3,5)
x[1:, ::2] = -99
print(x)
print(np.max(x[:,0]))
print(np.min(x[:,0]))
print(np.mean(x[:,0]))

print(np.sum(x[1,:]))


sor_a = np.array(a)[np.argsort(a)[::-1]]
print(sor_a)

[[  0   1   2   3   4]
 [-99   6 -99   8 -99]
 [-99  11 -99  13 -99]]
0
-99
-66.0
-283
[100  24  11  10   9   8   7   5   5   5   5   4   3   2   1   1]
