In [13]:
print("Hello World")

Hello World


In [1]:
print("asdf")

asdf


In [2]:
a = 1

In [3]:
a

1

In [4]:
b = [1,2,3,
4,5]

In [5]:
b

[1, 2, 3, 4, 5]

In [1]:
import random
import time

word = ['sky','earth','moon','flower','tree','apple','grape','garlic','onion','potato']
n = 1

input("[타자 게임] 준비되면 엔터!")
start = time.time()

while n < 11:
    print("문제", n)
    question = random.choice(word)
    print(question)
    user = input()
    if question == user:
        print("통과!")
        n += 1
    else:
        print("오타! 다시 도전!")

end = time.time()
et = end - start
print(f'타자시간: {et: .2f}초')

문제 1
garlic
통과!
문제 2
earth
통과!
문제 3
moon
통과!
문제 4
onion
통과!
문제 5
sky
통과!
문제 6
potato
통과!
문제 7
earth
통과!
문제 8
sky
통과!
문제 9
potato
통과!
문제 10
potato
통과!
타자시간:  20.12초


In [5]:
import numpy as np
x = np.array([3, 1, 2])
print(x)
print(type(x))

[3 1 2]
<class 'numpy.ndarray'>


In [13]:
c = [[1],[1,2]]
d = np.array([[1,1],[1,2]])

for x, y in d:
    print(x, y)

1 1
1 2


In [14]:
%ls

 C ����̺��� �������� �̸��� �����ϴ�.
 ���� �Ϸ� ��ȣ: FE35-8493

 c:\Users\admin\anacondatest ���͸�

2024-12-13  ���� 12:10    <DIR>          .
2024-12-13  ���� 11:54    <DIR>          ..
2024-12-13  ���� 11:56    <DIR>          .ipynb_checkpoints
2024-12-13  ���� 12:10             3,668 test.ipynb
               1�� ����               3,668 ����Ʈ
               3�� ���͸�  38,357,037,056 ����Ʈ ����


In [15]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [16]:
list1 = [1,3,5]
list2 = [2,4,6]
list1 + list2

[1, 3, 5, 2, 4, 6]

In [17]:
ndarray1 = np.array([1,3,5])
ndarray2 = np.array([2,4,6])
ndarray1 + ndarray2

array([ 3,  7, 11])

In [20]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
print(x+y)
print(x-y)
print(x*y)
print(x/y)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


In [24]:
print(x.shape)
print(x.dtype)
print(d.shape)
print(y/2.0)

(3,)
float64
(2, 2)
[1. 2. 3.]


In [ ]:
ndarray6 = np.array([[1,2,3],[4,5,6]])
ndarray6.ndim

2

In [35]:
ndarray6.shape

(2, 3)

In [39]:
a = np.array([[[1,2],[2,2]],[[3,2],[4,2]],[[5,2],[6,2]]])
print(a.shape)

(3, 2, 2)


In [3]:
import numpy as np

In [4]:
np.dot(4, 2)

8

In [6]:
ndar1 = np.array([3,2])
ndar2 = np.array([4,6])
np.dot(ndar1,ndar2)

24

In [8]:
ndar1 = np.array([[1,2],[3,4]])
ndar2 = np.array([[1,2],[3,4]])
np.dot(ndar1,ndar2)

array([[ 7, 10],
       [15, 22]])

In [9]:
np.matmul(ndar1,ndar2)

array([[ 7, 10],
       [15, 22]])

In [11]:
ndar1 = np.array([[1,2]])
ndar2 = np.array([[1,2],[3,4]])
np.matmul(ndar1,ndar2)

array([[ 7, 10]])

In [15]:
ndar2 = np.array([[[1],[2]],[[3],[4]]])
print(ndar2.shape)
print(ndar2.ndim)
a = ndar2.flatten()
print(a.ndim)
print(ndar2)

(2, 2, 1)
3
1
[[[1]
  [2]]

 [[3]
  [4]]]


In [19]:
ndarr = np.array([[1,2],[2,3],[3,4]])
ndarr.reshape(2,3)

array([[1, 2, 2],
       [3, 3, 4]])

In [20]:
ndarr.reshape(6,1)

array([[1],
       [2],
       [2],
       [3],
       [3],
       [4]])

In [21]:
ndarr.reshape(1,6)

array([[1, 2, 2, 3, 3, 4]])

In [22]:
np.random.randint(5, size=(2,4))

array([[3, 4, 4, 4],
       [4, 3, 3, 0]])

In [23]:
np.random.rand(2,4)

array([[0.65161544, 0.22628789, 0.7807272 , 0.99456305],
       [0.57733362, 0.68579629, 0.3889024 , 0.78121169]])

In [24]:
rng = np.random.default_rng()

In [25]:
rng.random()

0.37447771465317414

In [27]:
rng.integers(0, 10, (2,4))

array([[4, 4, 5, 2],
       [2, 9, 7, 0]], dtype=int64)

In [30]:
ndarr = np.array([[6,3],[5,2],[4,1]])
ndarr>3

array([[ True, False],
       [ True, False],
       [ True, False]])

In [32]:
ndarr = np.array([[6,3],[5,2],[4,1]])
ndarr[ndarr>3]

array([6, 5, 4])

In [37]:
ndarr[[[ True, False],
       [ True, False],
       [ True, False]]]

array([6, 5, 4])